---
title: "string_practice"
format: html
---

```{r}
rm(list = ls())
```

```{r}
library(tidyverse)
library(datapasta)
library(stringr)
library(lubridate)
```

```{r}
alarm_report <- data.table::data.table(
           date = c("2020-03-14", "2020-03-15", "2020-04-10", "2020-04-18"),
       building = c("Engineering-North","Bren Hall",
                    "Engineering-South","Engr-North"),
  alarm_message = c("10:02am -- HVAC system down, facilities management alerted",
                    "8:24am -- Elevator North out of service",
                    "12:41am -- Fire alarm, UCSB fire responded and cleared",
                    "9:58pm -- Campus point emergency siren, UCPD responded")
)
```

## everything
```{r}
string_fun <- alarm_report %>% 
  mutate(building = str_replace(building, pattern = "Engr", replacement = "Engineering")) %>%
  mutate(wing = str_split_i(building, "-", 2), building = str_split_i(building, "-", 1)) %>% 
  filter(str_detect(alarm_message, "responded") == TRUE) %>% 
  mutate(message = str_split_i(alarm_message, "--", 2), time_of_message = str_split_i(alarm_message, "--", 1)) %>% 
  select(-alarm_message) %>%
  mutate(date = ymd(date))
```

